---
- name: postgres
  hosts:
    - servers
  become: yes
  tasks:
    - include_role:
        name: postgres
        tasks_from: init_sql.yml
      vars:
        test_case: "store" # tpcc | store
        tpcc_scale: "32"

